### ISSUE TITLE
sane vs chokidar perfomance

### ISSUE THREAD

**Issue by evilebottnawi** [amasad/sane#98]
It would be great to see where and in what sane better than chokidar in performance.

**Comment by amasad** [comment]
Yeah would be cool to see. Although I'm not sure on what metrics would you rate file watchers? Maybe time until a file event is fired?

**Comment by evilebottnawi** [comment]
@amasad `time until a file event` is very good example. In general, it is advisable to look at all the performance indicators that affect performance. Now in `webpack` we use `chokidar`, but we have PR with `sane`. If the indicators determine greater performance then `chokidar` we raise this issue, since the performance in `webpack` permanent topic for disputes.

**Comment by stefanpenner** [comment]
Maybe anecdotal, but I have found sane using watchman to be the best performance. But the delta between the various modes and chokidar to be relatively minimal. 

I would be down for a thorough performance review and analsys, and would welcome such an analsysis.

I unfortunately don't believe this is a blocking issue for this project, and I believe both me and @amasad just don't have the bandwidth to do this today. Because of this, I am closing this issue.

Again, I would welcome the analysis be done, and if some good lesson can be learned, both @amasad and myself would love to learn it.
